### ISSUE TITLE
raw images

### ISSUE THREAD

**Issue by Songtao-Wang** [zhysora/PSGan-Family#1]
Thank you for the code，and where can I get the 9 pairs of raw images in GF-1 Dataset

**Comment by zhysora** [comment]
Thanks for your careful reading.
The raw images are under uploading, they will be available soon. 
Sorry for the late response.

**Comment by Songtao-Wang** [comment]
OK,thank you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhysora/PSGan-Family"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月18日(星期三) 晚上9:22
收件人:&nbsp;"zhysora/PSGan-Family"<PSGan-Family@noreply.github.com&gt;;
抄送:&nbsp;"寒号鸟"<2876754665@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zhysora/PSGan-Family] raw images (#1)





 
Thanks for your careful reading.
 The raw images are under uploading, they will be available soon.
 Sorry for the late response.

**Comment by zhysora** [comment]
The link of raw images is available now, thank you.

**Comment by Songtao-Wang** [comment]
Yes,thank you very much！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhysora/PSGan-Family"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月19日(星期四) 中午11:12
收件人:&nbsp;"zhysora/PSGan-Family"<PSGan-Family@noreply.github.com&gt;;
抄送:&nbsp;"寒号鸟"<2876754665@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zhysora/PSGan-Family] raw images (#1)





 
The link of raw images is available now, thank you.
