### ISSUE TITLE
About the network training stage.

### ISSUE THREAD

**Issue by JulioCeFer** [zhysora/PSGan-Family#11]
Dear Zhysora,

It would really help me out if you could take a look at my parameters for 9 (1+8) images from QB (your dataset), please?

I kept your original code (from PSGan-Family on GitHub), I just migrated to Google Colab (TF version: 1.15.2, GPU 0: Tesla P100-PCIE-16GB, Your runtime has 27.3 gigabytes of available RAM).
Unfortunately, the discrimi_loss assume “nan” quickly. Most of the time in epoch 1 (step 799  image/sec 26.8  remaining 596m discrim_loss nan gen_loss_GAN 0.00050416944 gen_loss_L1 309.3901), some times in epoch 2 and only once in epoch 7.
Parameters for training:
batch_size = 8
beta1 = 0.5
blk = 64
checkpoint = None
display_freq = 0
gan_weight = 1.0
gpus = 0
l1_weight = 100.0
lr = 0.0001
max_epochs = 50
max_steps = None
mode = train
ndf = 32
output_dir = /content/drive/MyDrive/Research/Psgan/Datasets/PSOutput/QB_train_64_psgan
progress_freq = 200
save_freq = 1000
seeds = 9001 #I’ve tried with and without it.
summary_freq = 0
test_count = 81
test_tfrecord = /content/my_data/QB_test_64.tfrecords
trace_freq = 0
train_count = 19297 #I’ve tried other values: 4821, 9647 and 1927 
train_tfrecord = /content/my_data/QB_train_64.tfrecords

Best Regards,

**Comment by zhysora** [comment]
Dear JulioCeFer,

Your parameters are correctly defined. If the "nan" problem can't be solved, you can have a try to simply remove the discrim_loss or try to train several epochs without the discrim_loss for warmup and then add it. Sorry for the delayed reply, and hope it will be helpful for you. 

Best Regards,
