### ISSUE TITLE
About data sets

### ISSUE THREAD

**Issue by JulioCeFer** [zhysora/PSGan-Family#3]
Dear Zhysora,
We came across your paper on PSGan which we found very interesting. We would be interested in comparing a method of ours with yours.
Unfortunately I am not able to access the Baidu website to download the raw images (only for people with phone numbers from China) at https://pan.baidu.com/s/1FfDSsxlBMUPsJXjbxKEIhQ.
Is there another alternative to download the raw images?

Thanks in advance for your help.
Best regards,

**Comment by zhysora** [comment]
Thanks for your comment. 
We have uploaded the data to Google Drive (https://drive.google.com/file/d/16owGAILT0uH8U5oMJrh2fwYGWUXhDpDc/view?usp=sharing). Hope this can help you.

Sorry for the inconvenience caused to you.

**Comment by JulioCeFer** [comment]
Dear Zhysora,

I made a request to access the google folder a few days ago.
Could you  please give me access to the folder please.

Thanks for advance.

**Comment by zhysora** [comment]
Dear JulioCeFer,

I didn't find the request from you in Google, and I modified the permission of this link for everyone can edit it. It's my first time using Google Drive. Hope it works.

Sorry for the late response.

**Comment by JulioCeFer** [comment]
Thank you very much.

It's working.
