### ISSUE TITLE
运行环境请教

### ISSUE THREAD

**Issue by jianlihua123** [zhysora/PSGan-Family#4]
作者您好，能否将运行环境及配置告知我呢，谢谢！

**Comment by zhysora** [comment]
Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-142-generic x86_64)
Python 3.6.11 

主要的python包:
Name                Version 
gdal                      3.1.2            
matplotlib            3.3.2                        
numpy                  1.19.1           
scikit-image         0.17.2          
scipy                     1.5.2            
tensorflow-gpu    1.3.0

**Comment by jianlihua123** [comment]
非常感谢您！
