### ISSUE TITLE
有关损失函数的一些问题

### ISSUE THREAD

**Issue by Dash-RSer** [zhysora/PSGan-Family#5]
请问是这篇论文的复现吗？PSGAN: A Generative Adversarial Network for Remote Sensing Image Pan-sharpening
我看到论文中说生成器的对抗损失是在小批量上求和，但是代码中好像是在小批量上做了平均？

**Comment by zhysora** [comment]
是复现，是平均

**Comment by zhysora** [comment]
论文上应该是漏了个1/n，非常抱歉。因为是估计的期望，肯定是平均的
