### ISSUE TITLE
About PSGAN with Colab...

### ISSUE THREAD

**Issue by JulioCeFer** [zhysora/PSGan-Family#8]
Dear Zhysora,

Do you know of any options for using PSGAN with Colab already developed? If you are not aware, do you believe that migrating to Colab is reasonably easy?

Best Regards,

**Comment by zhysora** [comment]
Sorry, I'm not aware of Colab. It seems like a kind of cloud service. If it meets the necessary computation and memory requirements, maybe can have a try.

**Comment by JulioCeFer** [comment]
I managed to put the code in Colab. It's working.
Thank you very much.
