### ISSUE TITLE
测试出来的结果相差很大，不知道是什么原因？

### ISSUE THREAD

**Issue by chen147258** [zhysora/PSGan-Family#9]
下面是我在QB测试出来的结果：
SAM: 24.7177
CC: nan
sCC: 0.9553
ERGAS: inf
Q4: 0.9694
为什么CC和ERGAS没有呢？其他结果也是比较差，是不是训练得不够多，要所有数据集都训练一次呢？

**Comment by zhysora** [comment]
检查一下输入数据处理是不是有问题。一般用默认参数就可以，数据集是单独训的

**Comment by chen147258** [comment]
我重新训练了一下，效果就很好，但是我只是把训练的log打印出来，设置了trace_freq和summary_freq为默认值，难道这个有影响吗？

**Comment by zhysora** [comment]
不会吧
